In [1]:
import torch

ModuleNotFoundError: No module named 'torch'

In [2]:
torch.set_default_dtype(torch.float64)

In [3]:
tensor_arr = torch.Tensor([[1,2,3], [4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
torch.is_tensor(tensor_arr)

True

In [5]:
torch.numel(tensor_arr)

6

In [6]:
tensor_uninitialized = torch.Tensor(2,2)
tensor_uninitialized

tensor([[1.2909e-311, 1.2909e-311],
        [1.2909e-311, 1.2909e-311]])

In [7]:
tensor_int = torch.tensor([5,2]).type(torch.IntTensor)
tensor_int

tensor([5, 2], dtype=torch.int32)

In [8]:
tensor_initialized = torch.rand(2,2)
tensor_initialized

tensor([[0.4891, 0.3772],
        [0.8810, 0.5078]])

In [9]:
tensor_short = torch.ShortTensor([1.0, 2.0, 3.0])
tensor_short

tensor([1, 2, 3], dtype=torch.int16)

In [10]:
tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [11]:
tensor_fill = torch.full((2, 6), fill_value=10)
tensor_fill

tensor([[10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10]])

In [12]:
tensor_of_ones = torch.ones([2,4], dtype=torch.int32)
tensor_of_ones

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [13]:
tensor_of_zeros = torch.zeros_like(tensor_of_ones)
tensor_of_zeros

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [14]:
tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [16]:
i = torch.tensor([[0, 1, 1], 
                 [2, 2, 0]])

In [17]:
v = torch.tensor([0, 1, 1], dtype=torch.float32)

In [18]:
sparse_tensor = torch.sparse_coo_tensor(i, v, [2, 5])

In [19]:
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([0., 1., 1.]),
       size=(2, 5), nnz=3, dtype=torch.float32, layout=torch.sparse_coo)

In [20]:
initial_tensor = torch.rand(2, 3)
initial_tensor

tensor([[0.0856, 0.0905, 0.9238],
        [0.1178, 0.3370, 0.1478]])

In [21]:
initial_tensor.fill_(10) 

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [22]:
initial_tensor.fill(10) 

AttributeError: 'Tensor' object has no attribute 'fill'

In [23]:
new_tensor = initial_tensor.add(5)
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [24]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [25]:
initial_tensor.add_(8)

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [26]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [27]:
x = torch.linspace(start=0.1, end=10, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [28]:
tensor_chunk = torch.chunk(x, 3, 0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [29]:
tensor1 = tensor_chunk[0]
tensor2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0, 4.0, 5.0])

torch.cat((tensor1, tensor2, tensor3), 0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [30]:
random_tensor = torch.Tensor([[10, 8, 30], [40, 5, 6], [12, 2, 21]])
random_tensor

tensor([[10.,  8., 30.],
        [40.,  5.,  6.],
        [12.,  2., 21.]])

In [31]:
random_tensor[0, 1]

tensor(8.)

In [32]:
random_tensor[1:, 1:]

tensor([[ 5.,  6.],
        [ 2., 21.]])

In [33]:
random_tensor.size()

torch.Size([3, 3])

In [34]:
# Resized tensor is looking at the same memory
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([10.,  8., 30., 40.,  5.,  6., 12.,  2., 21.])

In [35]:
resized_tensor = random_tensor.view(-1, 6)
resized_tensor

RuntimeError: shape '[-1, 6]' is invalid for input of size 9

In [36]:
resized_tensor.size()

torch.Size([9])

In [37]:
# Because memory is shared when we change random_tensor we see the change in resized_tensor
random_tensor[2,2] = 100
resized_tensor

tensor([ 10.,   8.,  30.,  40.,   5.,   6.,  12.,   2., 100.])

In [38]:
random_tensor

tensor([[ 10.,   8.,  30.],
        [ 40.,   5.,   6.],
        [ 12.,   2., 100.]])

In [39]:
random_tensor.shape

torch.Size([3, 3])

In [40]:
tensor_unsqueeze = torch.unsqueeze(random_tensor, 2)
tensor_unsqueeze

tensor([[[ 10.],
         [  8.],
         [ 30.]],

        [[ 40.],
         [  5.],
         [  6.]],

        [[ 12.],
         [  2.],
         [100.]]])

In [41]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [42]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [43]:
tensor_transpose = torch.transpose(initial_tensor, 0 ,1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [44]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [45]:
sorted_tensor

tensor([[  8.,  10.,  30.],
        [  5.,   6.,  40.],
        [  2.,  12., 100.]])

In [46]:
sorted_indices

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [47]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000], dtype=torch.float32)

In [48]:
tensor_abs = torch.abs(tensor_float)
tensor_abs

tensor([1.1000, 2.2000, 3.3000], dtype=torch.float32)

In [49]:
rand1 = torch.abs(torch.randn(2, 3))
rand2 = torch.abs(torch.randn(2, 3))

In [50]:
add1 = rand1 + rand2
add1

tensor([[1.2195, 0.5144, 2.0062],
        [1.8907, 1.7194, 1.2753]])

In [51]:
add2 = torch.add(rand1, rand2)
add2

tensor([[1.2195, 0.5144, 2.0062],
        [1.8907, 1.7194, 1.2753]])

In [52]:
tensor = torch.Tensor([[-1, -2, -3],
                     [1, 2, 3]])

In [53]:
tensor_div = torch.div(tensor, tensor + .3)
tensor_div

tensor([[1.4286, 1.1765, 1.1111],
        [0.7692, 0.8696, 0.9091]])

In [54]:
tensor_mul = torch.mul(tensor, tensor)
tensor_mul

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [55]:
tensor_clamp = torch.clamp(tensor, min=0.2, max=2)
tensor_clamp

tensor([[0.2000, 0.2000, 0.2000],
        [1.0000, 2.0000, 2.0000]])

In [56]:
t1 = torch.Tensor([1, 2])
t2 = torch.Tensor([10, 20])

In [57]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

In [58]:
matrix = torch.Tensor([[1, 2, 3],
                      [4, 5, 6]])
vector = torch.Tensor([0, 1, 2])

In [59]:
matrix_vector = torch.mv(matrix, vector)
matrix_vector

tensor([ 8., 17.])

In [60]:
another_matrix = torch.Tensor([[10, 30], 
                               [20, 0],
                               [0, 50]])

In [61]:
matrix_mul = torch.mm(matrix, another_matrix)
matrix_mul

tensor([[ 50., 180.],
        [140., 420.]])

In [62]:
torch.argmax(matrix_mul, dim=1)

tensor([1, 1])

In [63]:
torch.argmin(matrix_mul, dim=1)

tensor([0, 0])

## Conversion Between PyTorch and NumPy

In [64]:
import numpy as np
import torch

In [65]:
tensor = torch.rand(4, 3)
tensor

tensor([[0.7297, 0.1509, 0.5157],
        [0.5881, 0.7450, 0.4318],
        [0.8692, 0.4810, 0.9578],
        [0.2819, 0.9498, 0.1341]])

In [66]:
type(tensor)

torch.Tensor

In [67]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.72967231, 0.15089979, 0.51566723],
       [0.5881122 , 0.74504847, 0.43177772],
       [0.86924531, 0.4809552 , 0.95782747],
       [0.28191606, 0.94984546, 0.13410412]])

In [68]:
type(numpy_from_tensor)

numpy.ndarray

In [69]:
torch.is_tensor(tensor)

True

In [70]:
torch.is_tensor(numpy_from_tensor)

False

In [71]:
# Shares memory with tensor
numpy_from_tensor[0, 0] = 100.0
numpy_from_tensor

array([[100.        ,   0.15089979,   0.51566723],
       [  0.5881122 ,   0.74504847,   0.43177772],
       [  0.86924531,   0.4809552 ,   0.95782747],
       [  0.28191606,   0.94984546,   0.13410412]])

In [72]:
tensor

tensor([[100.0000,   0.1509,   0.5157],
        [  0.5881,   0.7450,   0.4318],
        [  0.8692,   0.4810,   0.9578],
        [  0.2819,   0.9498,   0.1341]])

In [73]:
numpy_arr = np.array([[1.0, 2.0, 3.0],
                      [10.0, 20.0, 30.0],
                      [100.0, 200.0, 300.0]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [74]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [75]:
type(tensor_from_numpy)

torch.Tensor

In [76]:
torch.is_tensor(tensor_from_numpy)

True

In [77]:
# Also shares memory with numpy array
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [78]:
numpy_arr

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [79]:
np_array_one = np.array([4, 8])
np_array_one

array([4, 8])

In [80]:
tensor_from_array_one = torch.as_tensor(np_array_one)
tensor_from_array_one

tensor([4, 8], dtype=torch.int32)

In [81]:
# Same memory
np_array_one[1] = 5
np_array_one

array([4, 5])

In [82]:
tensor_from_array_one

tensor([4, 5], dtype=torch.int32)

In [83]:
np_array_two = np.array([2, 2])
np_array_two

array([2, 2])

In [84]:
# Does not share memory
tensor_from_array_two = torch.tensor(np_array_two)
tensor_from_array_two

tensor([2, 2], dtype=torch.int32)

In [85]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [86]:
tensor_from_array_two

tensor([2, 2], dtype=torch.int32)