In [1]:
import numpy as np
import torch
import torch.nn as nn

In [9]:
W = torch.rand(6)

x = torch.tensor([10.0, 10.0, 10.0, 10.0, 10.0, 10.0])

b = torch.tensor(3)

In [10]:
W

tensor([0.5291, 0.0157, 0.4510, 0.2349, 0.9775, 0.5479])

In [11]:
y = W*x +b

In [12]:
y

tensor([ 8.2914,  3.1573,  7.5101,  5.3493, 12.7753,  8.4786])

In [15]:
W1 = torch.tensor(6)
W2 = torch.tensor(6)
W3 = torch.tensor(6)

x1 = torch.tensor([2, 2, 2])
x2 = torch.tensor([3, 3, 3])
x3 = torch.tensor([4, 4, 4])

b = torch.tensor(10)

In [16]:
W1, W2, W3

(tensor(6), tensor(6), tensor(6))

In [17]:
intermediate_value = W1 *x1 + W2 * x2
intermediate_value

tensor([30, 30, 30])

In [18]:
final_value = W1 *x1 + W2 * x2 + W3 *x3 + b
final_value

tensor([64, 64, 64])

In [19]:
import hiddenlayer as hl