In [3]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [4]:
tf.enable_eager_execution()

In [5]:
tf.executing_eagerly()

True

In [8]:
W = tf.Variable(6, name = 'var_W')

x = tf.constant([10, 10], name = 'x')

b = tf.Variable(3, name = 'constant_b')

In [9]:
W

<tf.Variable 'var_W:0' shape=() dtype=int32, numpy=6>

In [10]:
x

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [11]:
b

<tf.Variable 'constant_b:0' shape=() dtype=int32, numpy=3>

In [12]:
y = W * x + b

In [13]:
y

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([63, 63])>

In [14]:
print(W*x)

tf.Tensor([60 60], shape=(2,), dtype=int32)


In [15]:
np_result = np.multiply(W, x)
np_result

array([60, 60])

In [16]:
W.numpy()

6